language: c
script: asdf plugin-test logtalk https://github.com/LogtalkDotOrg/asdf-logtalk.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
